abstract class AppState {}
class AppIntialState extends AppState{}
class AppBottomSheetNavigationBar extends AppState{}
class AppCreateDatabase extends AppState{}
class AppBottomSheetState extends AppState{}
class AppGetDatabase extends AppState{}
class AppInsertToDataBase extends AppState{}
class AppUpdateDataBase extends AppState{}
class AppDeleteDataBase extends AppState{}